version: '3.8'

services:
  commodities:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: commodities-app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "90:80"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
